[FIX] if a product already have a code do not change it
OCA/product-variant pull request #195
Opened 2020-11-29 22:18 UTC by sebastienbeau

When modify a attribute value (fixing a typo for example).
The onchange will change the code of the attribute.
This may generate a lot of mistake as user can change the code of an attribute value by mistake and set a wrong value

2020-11-29 22:20 UTC, sebastienbeau commented
@pedrobaeza @bealdav @alfredoavanzosc

2020-11-30 07:53 UTC, bealdav approved these changes

2020-11-30 07:58 UTC, pedrobaeza requested changes
I think this is a change of behavior, as I find legit cases both on previous code and new one, depending on the users. If you add this, you should do it configurable (via a system parameter for example).

2022-02-07 14:05 UTC, bealdav commented
Please @sebastienbeau.

Could you close or any option please ?

2022-02-07 14:08 UTC, closed without merging