[13.0][ADD] Add digits to avoid round and better treathement of product variant p…
OCA/product-variant pull request #267
Opened 2022-07-12 07:17 UTC by sergioeix

…rice

without this a a price like 0.0758 on the filed fix_price on variant form is shown like 0.01

2022-07-12 07:45 UTC, sergioeix commented
Hi guys can you review please ?
@cubells @sergio-teruel @tafaRU

2022-07-12 08:13 UTC, sergio-teruel approved these changes

2022-07-13 07:30 UTC, tafaRU approved these changes

2022-07-13 14:12 UTC, cubells requested changes
:+1: 

LGTM

Code review and test

2022-07-13 14:13 UTC, cubells approved these changes
:+1: 

LGTM

Code review and test

2022-07-17 09:38 UTC, pedrobaeza commented
/ocabot merge patch

2022-07-17 09:51 UTC, merged