16.0 mig product variant sale price
OCA/product-variant pull request #281
Opened 2023-02-01 10:48 UTC by RabbitJon-S73

Standard migration to 16.0.

Added https://github.com/OCA/product-variant/pull/280

2023-02-23 12:04 UTC, RabbitJon-S73 commented
@Kev-Roche there is any issue with the pre-commit in v16.0?

2023-02-23 19:41 UTC, Kev-Roche commented
@RabbitJon-S73 I m not the right person for this kind of question sorry ;)

2023-03-03 07:08 UTC, RabbitJon-S73 commented
@sergio-teruel could you review?

2023-03-03 09:18 UTC, sergio-teruel approved these changes

2023-03-16 13:02 UTC, BT-anieto requested changes
Thanks for your work! Some changes to be done, since there are some changes to do in the migration which have not been applied. Check out the migration page Check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

On the other hand remember to squash the commits as indicted in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

2023-03-16 13:02 UTC, BT-anieto commented on product_variant_sale_price/models/product_product.py
> +                price = product.uom_id._compute_price(price, context_uom)
Why change? We should minimise the code changes in a migration and the code was proper?

2023-03-16 13:02 UTC, BT-anieto commented on product_variant_sale_price/models/product_product.py
> +                price = product.uom_id._compute_price(price, context_uom)
Why change? We should minimise the code changes in a migration and the code was proper?

2023-03-16 13:02 UTC, BT-anieto commented on product_variant_sale_price/tests/test_product_product.py
> +        self.product_template.product_variant_ids.invalidate_cache()
Check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

invalidate_cache is deprecated

2023-03-16 13:02 UTC, BT-anieto commented on product_variant_sale_price/tests/test_product_product.py
> +        self.product_red.flush()
Check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

flush is deprecated

2023-03-16 17:03 UTC, RabbitJon-S73 commented on product_variant_sale_price/models/product_product.py
> +                price = product.uom_id._compute_price(price, context_uom)
https://github.com/OCA/product-variant/pull/280 I took this changes, I think is the correct behaviour

2023-03-17 07:56 UTC, BT-anieto commented on product_variant_sale_price/models/product_product.py
> +                price = product.uom_id._compute_price(price, context_uom)
Great! Thank you very much. Let me check.

By the way, tests are not passing. I will rereview when they pass.

2023-03-17 13:06 UTC, RabbitJon-S73 commented on product_variant_sale_price/models/product_product.py
> +                price = product.uom_id._compute_price(price, context_uom)
Hey, I solved the problem with the test. I also saw your review on  https://github.com/OCA/product-variant/pull/280 and I changed the `.get` after being once checked

2023-03-21 16:37 UTC, BT-anieto commented on product_variant_sale_price/models/product_product.py
> +                price = product.uom_id._compute_price(price, context_uom)
Thx @RabbitJon-S73. I asked a question in #280 because I was a bit surprised about the change. Still not an answer, but the code looks good to me :)

2023-03-21 16:39 UTC, BT-anieto reviewed
LGTM

2023-03-21 16:40 UTC, BT-anieto approved these changes

2023-03-27 11:28 UTC, antoniocanovas approved these changes
Functional review OK

2023-04-14 06:40 UTC, ecino commented
Oh, I didn't see this one because it's not linked in the migration issue #272 . I did also a migration myself in which I also included some view changes that  I think make sense and help better use the functionality. However here there are some changes in the `uom` computation part that I think are good. Would you like to review and integrate my changes as well in your PR? See #290

2023-04-14 06:47 UTC, ecino commented
I went ahead and integrated your corrections into my PR (by cherry-picking and rebasing).

2023-04-21 09:01 UTC, HugoCordobaLeal commented
LGTM! (code review)

2023-04-21 09:01 UTC, hugo-cordoba approved these changes

2023-06-16 07:47 UTC, hildickethan-S73 commented on product_variant_sale_price/models/product_product.py
> +        return product_tmpl
better as multi

2023-06-22 11:34 UTC, RabbitJon-S73 commented on product_variant_sale_price/models/product_product.py
> +        return product_tmpl
@hildickethan-S73 Done!

2023-06-22 11:37 UTC, ecino commented
@RabbitJon-S73 I thought you would close this one in favor of #290

2023-07-09 21:29 UTC, maxgrassi commented
Bug report: Tested and this is not working in version 16: "This module also hides sale price at product template level when has more than one variant."
The product price can be set at product templete level and this overwrites all the prices that have been set at product variant level.

2023-10-02 11:12 UTC, closed without merging