[16.0][MIG] product_variant_configurator: Migration to 16.0
OCA/product-variant pull request #286
Opened 2023-03-03 19:10 UTC by SergioPSV

Standard Migration

2023-03-03 19:11 UTC, pedrobaeza commented
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

2023-03-03 19:36 UTC, SergioPSV commented
@OCA/core-maintainers

2023-03-03 19:47 UTC, SergioPSV commented
@mariadforgeflow Can you review the code?

2023-03-03 19:49 UTC, pedrobaeza commented
Please see my previous comment: https://github.com/OCA/product-variant/pull/286#issuecomment-1453996944

2023-03-03 20:13 UTC, SergioPSV commented
@pedrobaeza Added the history of commits

2023-03-03 20:15 UTC, pedrobaeza commented
/ocabot migration product_variant_configurator

2023-05-31 18:39 UTC, isserver1 commented
Hey @SergioPSV thank you for your contribution! 
Looks like runboat is down. Could you please push something to this PR to bring it up again?
We will do the functional testing

2023-06-01 15:10 UTC, SergioPSV commented
@isserver1 runboat restart successfully

2023-06-02 09:12 UTC, hieulucky111 requested changes

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +    can_create_product = fields.Boolean(compute="_compute_can_be_created", store=False)
should remove store=False while it is default.

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +            if rec.product_id:
we can do like `if rec.product_id or not rec.product_tmpl_id`:

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +    def _compute_price_extra(self):
i think we can re-use function `_compute_can_be_created`

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +        if self.product_tmpl_id:
should add `self.ensure_one()`?

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +        if self.product_id:
should use `self.ensure_one()`?

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +            return {"domain": {"product_id": []}}
i think this doesn't work anymore from version 15. Use onchange to set the domain.

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +        else:
`elif self.product_id and self.product_id.product_tmpl_id != self.product_tmpl_id and not self.env.context.get("not_reset_product") =>                     self.product_id = False`

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +        return {"domain": {"product_id": domain}}
i think this doesn't work anymore.

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +            return {"domain": {"product_id": []}}
same above.

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +            return {"domain": {"product_id": domain}}
same above.

2023-06-02 09:12 UTC, hieulucky111 commented on product_variant_configurator/models/product_configurator.py
> +        return {"domain": {"product_id": domain}}
same above.

2023-07-02 05:54 UTC, maxgrassi commented
Hi, I tested  and it works great! I have a suggestion: Exclude/Filter variant for attribute combination. Because the standard behavior in the Sales app (sales order) or ecommerce app (product page) when configuring attributes and variants it always shows all product configurations as set on the master product (product.template) and does not filter products that actually exist at the product.product variant level.

When configuring product attributes and variants the system does not filter the available combinations but lists all combinations even those that do not exist. This is quite confusing  for example in complex configurable products.

2023-08-25 07:13 UTC, LoisRForgeFlow commented
@SergioPSV Could you attend the last two reviews? Thanks!

2023-09-08 14:13 UTC, EvaSForgeFlow commented
Continuation of this PR: https://github.com/OCA/product-variant/pull/303

2023-09-20 13:27 UTC, LoisRForgeFlow commented
> Hi, I tested and it works great! I have a suggestion: Exclude/Filter variant for attribute combination. Because the standard behavior in the Sales app (sales order) or ecommerce app (product page) when configuring attributes and variants it always shows all product configurations as set on the master product (product.template) and does not filter products that actually exist at the product.product variant level.
> 
> When configuring product attributes and variants the system does not filter the available combinations but lists all combinations even those that do not exist. This is quite confusing for example in complex configurable products.

I think there could be performance issues for products with several attributes in which the combination of all them is really huge. So I see such a feature out of the scope of the migration, it could be added in a separate PR and discuss the possibilities there.

2023-10-02 10:59 UTC, hildickethan-S73 commented
You can close this as https://github.com/OCA/product-variant/pull/303 is merged

2024-03-10 12:20 UTC, closed without merging