[16.0][MIG] product_variant_sale_price: Migration to 16.0
OCA/product-variant pull request #290
Opened 2023-04-13 14:28 UTC by ecino

Only adapted the tests, functionality is working without modifications.

2023-04-14 06:48 UTC, ecino commented
This PR includes also the work done by RabbitJon-S73 in #281 but goes a little bit further by improving the views.

2023-04-18 08:55 UTC, RabbitJon-S73 commented
@ecino LGTM, ask the other reviewers to have a look and if they find it ok im closing my PR to avoid conflicts.

2023-04-20 14:06 UTC, hitrosol approved these changes
Tested in runboat, LGTM.

2023-04-21 09:01 UTC, HugoCordobaLeal commented
Hi! In my opinion, you should propose the improvements in the other PR and have them added in the PR that was done in the first place.

Regards!

2023-05-08 14:10 UTC, enriquemartin approved these changes

2023-05-11 14:14 UTC, aleuffre commented
@ecino Could you rebase and solve the conflicts please?

2023-05-11 14:50 UTC, aleuffre commented
Warning during installation: 

```
2023-05-11 14:43:45,436 20 WARNING devel odoo.api.create: The model odoo.addons.product_variant_sale_price.models.product_product is not overriding the create method in batch 
```

2023-06-05 11:21 UTC, ecino commented
Thanks for the reviews and sorry for the delay in my answer. I corrected all reported issues.

2023-06-05 11:29 UTC, aleuffre approved these changes
Code review, LGTM

2023-06-19 12:19 UTC, FrankC013 requested changes

2023-06-19 12:19 UTC, FrankC013 commented on product_variant_sale_price/models/product_product.py
> +    fix_price = fields.Float()
### Proposed Changes for Implementation

These proposals are aimed at how this new implementation will impact the _price_extra_ field of the **product** module. 
The _price_extra_ field, with the changes you have proposed, will stop being displayed but will not erase its data, a fact with which I agree, since if the module is uninstalled, access should still be had to the previously stored information. However, the **sale.order.line** module calculates the _price_unit_ by adding the value of _price_extra_ and this can generate inconsistencies if the field has old data stored.

https://github.com/odoo/odoo/blob/5ac58ebf983c1c02019253c0430fde3502e13e7c/addons/product/models/product_product.py#L609-L628

To avoid each user having to perform a data migration, I think the most appropriate would be to modify the __compute_product_price_extra()_ method of the _price_extra_ in the **product.product** to ensure that in other models it does not take the obsolete value from the database. The **product.product**'s _price_extra_ field is a `store=False`, so it will not impact the information of the _price_extra_ stored in the **product.template.attribute.value**. 
For this reason, I propose add the following change:

```python
    def _compute_product_price_extra(self):
        for product in self:
            product.price_extra = 0.0
```

2023-06-19 12:19 UTC, FrankC013 commented on product_variant_sale_price/models/product_product.py
> +
On the other hand, within the sale module it would be advisable to hide the badge that is generated when the _price_extra_ is informed.

https://github.com/odoo/odoo/blob/5ac58ebf983c1c02019253c0430fde3502e13e7c/addons/sale/views/variant_templates.xml#L119C1-L142

For this reason and to continue with the structure of our changes, I propose modifying the __get_combination_info()_ method so that it always reports that the `price_extra = 0.0`

```suggestion
    def _get_combination_info(self, combination=False, product_id=False, add_qty=1, pricelist=False, parent_combination=False, only_template=False):
        res = super(ProductTemplate, self)._get_combination_info(combination, product_id, add_qty, pricelist, parent_combination, only_template)
        res['price_extra'] = 0.0
        return res
```

I await your feedback to know what you think about this!! :D

2023-06-19 12:34 UTC, eantones commented on product_variant_sale_price/models/product_product.py
> +    fix_price = fields.Float()
LGTM!

2023-06-19 12:34 UTC, eantones commented on product_variant_sale_price/models/product_product.py
> +
LGTM!

2023-06-20 05:57 UTC, ecino commented on product_variant_sale_price/models/product_product.py
> +
Thank you for the very good suggestions. I applied the suggested changes.

2023-06-20 05:59 UTC, ecino commented
I applied the nice suggestions from @FrankC013 and also added a new Action that can be very handy for controlling which variant will be the price reference in case the user prefers not to have the cheapest variant as the reference price (which is the default behaviour).

2023-06-29 11:18 UTC, ecino commented
Is there something else preventing the merge? Can someone give the final review here? Thanks!

2023-06-30 15:53 UTC, aleuffre approved these changes

2023-07-09 21:31 UTC, maxgrassi commented
Bug report: Tested and this is not working in version 16: "This module also hides sale price at product template level when has more than one variant."
The product price can be set at product templete level and this overwrites all the prices that have been set at product variant level.

2023-07-10 04:49 UTC, maxgrassi commented
Suggestion: "Compare to Price?" should be moved at variant level.

2023-07-10 05:59 UTC, ecino commented
> Bug report: Tested and this is not working in version 16: "This module also hides sale price at product template level when has more than one variant." The product price can be set at product templete level and this overwrites all the prices that have been set at product variant level.

Where did you quote this from? In my perspective it's not a bug but the way it was made. A tooltip is also displayed for warning about this behaviour, which is totally fine in my opinion.

2023-07-10 06:10 UTC, ecino commented
> Suggestion: "Compare to Price?" should be moved at variant level.

This is a good suggestion, however the "Compare to price" field is defined in the "Website sale" module which would add a potential not needed dependency. A new bridge module extending this functionality would be better than integrating this inside this module.

2023-07-10 07:17 UTC, aleuffre approved these changes

2023-07-10 07:43 UTC, maxgrassi commented
> > Bug report: Tested and this is not working in version 16: "This module also hides sale price at product template level when has more than one variant." The product price can be set at product templete level and this overwrites all the prices that have been set at product variant level.
> 
> Where did you quote this from? In my perspective it's not a bug but the way it was made. A tooltip is also displayed for warning about this behaviour, which is totally fine in my opinion.

I Took is from here: https://github.com/ecino/product-variant/tree/14.0/product_variant_sale_price 
I understand this is V14 and in V16 is going to be different however it is much safer to hide the sale price at product template level. If you have complex variants with many different prices and you touch by mistake the price in the product template (can happen), you end to loose all the prices set in the variants. This is a very dangerous behavior in everyday use. At least leave the possibility to not edit the price in the product template level.

2023-07-11 17:52 UTC, eantones commented
I think the change https://github.com/OCA/product-variant/commit/39c984ced2376a37b435b866925822e45e8499c3#diff-9928710829783336eb5c9e25e03423f41edc07f81ac7051fbb6e799e8a2394f6 you introduced after the fixes proposed by @FrankC013 is getting in the way for me to approve this PR. It introduces a new logic that needs to be understood and tested, thereby delaying the overall PR approval. But, anyway, in my opinion, this change is indeed an improvement and it should be in a separate PR, as the current one is solely for the module's migration. If that particular commit were absent, my approval would be immediate.
In any case, thanks @ecino for your job :-)

2023-07-13 08:18 UTC, ecino commented
> Suggestion: "Compare to Price?" should be moved at variant level.

Here is your feature request, in a separate module : #297

2023-07-13 08:32 UTC, ecino commented
> > > Bug report: Tested and this is not working in version 16: "This module also hides sale price at product template level when has more than one variant." The product price can be set at product templete level and this overwrites all the prices that have been set at product variant level.
> > 
> > 
> > Where did you quote this from? In my perspective it's not a bug but the way it was made. A tooltip is also displayed for warning about this behaviour, which is totally fine in my opinion.
> 
> I Took it from here: https://github.com/ecino/product-variant/tree/14.0/product_variant_sale_price I understand this is V14 and in V16 is going to be different however it is much safer to "avoid to edit" the sale price at product template level. If you have complex variants with many variants and many different prices and you touch by mistake the price in the product template (can happen), you end to loose all the prices set in the variants. This is a very dangerous behavior in everyday use. At least leave the possibility to turn off the edit mode for the price in the product template level.

I think it's best to let the user decide. A warning message is displayed below the field and is enough in my opinion.

![image](https://github.com/OCA/product-variant/assets/8435180/d580bafd-37be-4cb8-b331-20810764cde6)

2023-07-13 08:38 UTC, ecino commented
@eantones @FrankC013 Separated the features additions in #298 

This PR is only the migration of the module.

2023-07-13 12:05 UTC, eantones approved these changes

2023-07-13 12:09 UTC, eantones requested changes
@ecino the code added by @FrankC013 were not new features, they were fixes so they should be included in the migration module

2023-07-13 14:05 UTC, ecino commented
Sorry, I misunderstood your last comment then. Now I think I get it, you only want to split the server action I added, right?

2023-07-13 14:06 UTC, eantones commented
Yes, thanks

2023-07-13 17:37 UTC, eantones commented
LGTM

2023-07-13 17:37 UTC, eantones approved these changes

2023-07-17 12:37 UTC, FrankC013 approved these changes

2023-08-08 15:54 UTC, aleuffre commented
@OCA/product-maintainers can this be merged please?

2023-09-07 17:05 UTC, willmakenoise commented
@OCA/product-maintainers Any chance this can be merged? 😀

2023-09-18 12:22 UTC, eantones commented
@OCA/product-maintainers can we merge this PR? :-)

2023-10-02 11:00 UTC, hildickethan approved these changes

2023-10-02 11:08 UTC, hildickethan-S73 commented
It would be better if the last commit followed the usual commit guidelines
`[IMP] product_variant_sale_price: Set price_extra to 0` instead of `[IMP] Apply suggested changes from FrankC013 to put price_extra to 0.0`
You can add who suggested the changes in the description of the commit rather than the message itself

2023-10-03 07:31 UTC, manuelcalerosolis commented
LGTM

2023-10-03 07:31 UTC, manuelcalerosolis approved these changes

2023-10-09 10:31 UTC, fuentes73 commented
@ecino could you resolve the conflicts? You don't need to edit the README.md it's done by the oca bot.

2023-10-16 07:23 UTC, ecino commented
PR Fixed.

2023-10-24 14:47 UTC, LoisRForgeFlow commented
@ecino It seems that tests are failing, can you have a look?

2023-10-26 11:34 UTC, ecino commented
Apparently it causes problem with the `product_variant_name` module that was introduced lately. I will check when I have time.

2023-12-11 12:58 UTC, uvid-sinisa commented
@ecino Looks like module product_variant_name adds field "Name" to product.product as required but tests in product_variant_sale_price create product_products without name.
Would the appropriate fix be to just add some name when creating the product_product in tests?

2023-12-11 13:40 UTC, ecino commented
Thanks for the hint. Can we merge now?

2024-01-05 15:53 UTC, aleuffre commented
@OCA/product-maintainers

2024-02-14 11:59 UTC, HaraldPanten commented
/ocabot merge nobump

2024-02-14 12:00 UTC, HaraldPanten commented
@etobella could you merge this one? I forgot I don't have permissions here! 😂

2024-02-14 12:02 UTC, etobella commented
/ocabot merge nobump

2024-02-14 12:03 UTC, HaraldPanten approved these changes

2024-02-14 12:06 UTC, merged