[16.0][ADD] Module for displaying price comparisons per product variant
OCA/product-variant pull request #297
Opened 2023-07-13 08:17 UTC by ecino

2023-07-13 10:32 UTC, maxgrassi commented
LGTM

2023-07-13 12:02 UTC, eantones commented
LGTM

2023-11-13 15:30 UTC, ecino commented
Anyone else willing to review this?

2023-11-17 13:19 UTC, giarve approved these changes

2023-11-17 13:21 UTC, giarve commented
If you want the bot to mark this as approved you have to click on the commit and review the changes from there. If you only write a message it is not enough, mantainers are not notified. Also, runboat job should be restarted as it is stuck at "pending".

2024-03-25 10:52 UTC, ecino commented
Can we merge this?

2024-08-06 10:03 UTC, ecino commented
Can we merge instead of closing, when everything seems ok?

2024-08-06 18:35 UTC, pedrobaeza requested changes
This must be in OCA/e-commerce, and start with `website_sale_`, as the dependency is clear.

2025-01-19 12:28 UTC, closed without merging