[FIX] product_variant_configurator: returning domains in onchange doesn't work anymore
OCA/product-variant pull request #337
Opened 2024-03-07 10:10 UTC by jdoutreloux

2024-03-07 12:29 UTC, ThomasBinsfeld requested changes
Please fix pre-commit

2024-03-07 12:29 UTC, ThomasBinsfeld commented on product_variant_configurator/models/product_configurator.py
> +                rec.product_id_configurator_domain = []
```suggestion
                rec.product_id_configurator_domain = TRUE_DOMAIN
```

from odoo.osv.expression

2024-03-07 12:29 UTC, ThomasBinsfeld commented on product_variant_configurator/models/product_configurator.py
> +                domain, cont = product_obj._build_attributes_domain(
```suggestion
                domain, _cont = product_obj._build_attributes_domain(
```

Prefix unused variable with `_`

2024-03-07 12:29 UTC, ThomasBinsfeld commented on product_variant_configurator/tests/test_product_variant_configurator.py
> +        # res = product._onchange_product_tmpl_id_configurator()
Remove or restore commented code.

2024-03-07 14:42 UTC, ThomasBinsfeld approved these changes

2024-03-12 07:57 UTC, FrancoMaxime approved these changes

2024-04-02 11:41 UTC, victoralmau approved these changes

2024-04-02 18:13 UTC, pedrobaeza commented
/ocabot merge patch

2024-04-02 18:18 UTC, merged