[18.0][MIG] product_variant_sale_price: Migration to 18.0
OCA/product-variant pull request #374
Opened 2024-11-20 10:18 UTC by NICO-SOLUTIONS

standard migration

2025-02-07 09:20 UTC, ph-obs commented
Hi @NICO-SOLUTIONS. May I ask if you are still working on this, or if ther are any updates?

2025-02-07 10:26 UTC, NICO-SOLUTIONS commented
> Hi @NICO-SOLUTIONS. May I ask if you are still working on this, or if ther are any updates?

Feel free to review...

2025-02-13 15:55 UTC, rousseldenis commented
/ocabot migration product_variant_sale_price

2025-02-13 16:07 UTC, rousseldenis commented on product_variant_sale_price/__manifest__.py
> +    "version": "18.0.1.1.0",
Could you reset to `18.0.1.0.0`? Thanks

2025-02-13 16:07 UTC, rousseldenis commented on product_variant_sale_price/models/product_product.py
> +        for product in self:
```suggestion
        self.price_extra = 0.0
```

2025-02-13 16:07 UTC, rousseldenis commented on product_variant_sale_price/models/product_product.py
> +            product_tmpl._update_fix_price(single_vals)
IMHO, this should be improved.

Instead, I would have looked at `_create_variant_ids()` and `_prepare_variant_values()` in order to avoid too much writes as using variant `create()` instead.

2025-02-13 16:09 UTC, rousseldenis commented on product_variant_sale_price/models/product_product.py
> +            product_tmpl._update_fix_price(single_vals)
@tafaRU @ecino @carlosdauden

2025-02-13 17:51 UTC, NICO-SOLUTIONS commented on product_variant_sale_price/models/product_product.py
> +            product_tmpl._update_fix_price(single_vals)
@rousseldenis please let me know, if the IMP-commit contains what you were thinking of

2025-04-17 13:59 UTC, matteonext approved these changes
functional ok

2025-05-01 13:59 UTC, ecino approved these changes
LGTM :+1:

2025-05-12 10:16 UTC, micheledic approved these changes

2025-05-14 07:06 UTC, AlienAtSystem requested changes

2025-05-14 07:06 UTC, AlienAtSystem commented on product_variant_sale_price/models/product_product.py
> +            pricelist,
pricelist was removed as a kwarg from _get_combination_info in Odoo18. It needs to be removed or this call will crash

2025-05-14 07:46 UTC, AlienAtSystem approved these changes

2025-05-15 12:17 UTC, jappi00 commented
LGTM

2025-05-30 12:04 UTC, FrancoMaxime reviewed
Hi @NICO-SOLUTIONS, thanks for all your work. great Job

2025-05-30 12:04 UTC, FrancoMaxime commented on product_variant_sale_price/__manifest__.py
> +    "author": "Tecnativa, " "Odoo Community Association (OCA)",
```suggestion
    "author": "Tecnativa, Odoo Community Association (OCA)",
```

2025-05-30 12:04 UTC, FrancoMaxime commented on product_variant_sale_price/models/product_product.py
> +                )
```suggestion
         tmpl.product_variant_ids.with_context(skip_update_fix_price=True).write(
                    {"fix_price": tmpl.list_price}
                )
```

2025-05-30 12:04 UTC, FrancoMaxime commented on product_variant_sale_price/models/product_product.py
> +                )
I think as its the same value for each product_variant_ids, its more optimized to make only one write for all of them. No?

2025-05-30 12:04 UTC, FrancoMaxime commented on product_variant_sale_price/models/product_product.py
> +class ProductProduct(models.Model):
@rousseldenis Hi Denis, i didn't found an answer in the [contribution guide](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#modules). But should the two classes be split into two files?

2025-05-30 13:34 UTC, NICO-SOLUTIONS commented on product_variant_sale_price/models/product_product.py
> +class ProductProduct(models.Model):
just let me know if you want to have this separated

2025-06-26 05:04 UTC, ecino commented
@OCA/product-maintainers Can we merge this one?

2025-06-30 08:20 UTC, FrancoMaxime commented on product_variant_sale_price/models/product_product.py
> +class ProductProduct(models.Model):
As you wish, IMO I prefer split into 2 files. But there is not standard rule for that

2025-06-30 11:31 UTC, NICO-SOLUTIONS commented on product_variant_sale_price/models/product_product.py
> +class ProductProduct(models.Model):
@FrancoMaxime 
methods are splitted now in 2 files.

2025-07-02 14:16 UTC, NICO-SOLUTIONS commented
@OCA/product-maintainers 
can we merge this one please?

2025-08-20 14:50 UTC, AEstLo commented
@simahawk do you mind to merge this one?

2025-08-20 17:08 UTC, PaulGoubert approved these changes
Funtionnal review OK. 
thank you Nico-Solutions

2025-08-21 09:33 UTC, simahawk commented
@NICO-SOLUTIONS could you please rewrite the last commits to include the module name as per our guidelines? 
Thanks!

<img width="738" height="560" alt="image" src="https://github.com/user-attachments/assets/074855c3-063e-4762-a36b-ca45a2d1e2dc" />

2025-08-21 11:42 UTC, NICO-SOLUTIONS commented
@simahawk 
yeah sure.... rewriting of the mentioned pr´s done!

2025-08-28 15:10 UTC, AEstLo commented
so can this be merged? @simahawk 
Thanks in advance!

2025-08-29 05:54 UTC, simahawk commented
/ocabot merge nobump

2025-08-29 05:59 UTC, merged