[9.0][NEW] product_variant_standard_price_update
OCA/product-variant pull request #48
Opened 2016-12-15 21:36 UTC by sergio-teruel

New module to update cost price for all product variants

cc @tecnativa
@rafaelbn please can you review??
Thanks

2016-12-15 22:42 UTC, rafaelbn commented
Hi, I cannot test it because runbot doesn't build. It has state "skipped", maybe @pedrobaeza could help as this happended in OCA/pos similar and it was because an travis issue. In fact https://runbot.odoo-community.org/runbot/repo/github-com-oca-product-variant-137 v9 an d v10 are broken

2016-12-15 23:46 UTC, pedrobaeza requested changes
The wizard is not needed with the new approach.

2016-12-15 23:46 UTC, pedrobaeza commented on product_variant_standard_price_update/i18n/es.po
> +msgstr "Diferente coste por variante"
Keep the span tags.

2016-12-15 23:46 UTC, pedrobaeza commented on product_variant_standard_price_update/models/product.py
> +            if cost.count(cost[0]) == len(cost):
This will fail if no variant (for example, with the product_variant_configurator module)

2016-12-15 23:46 UTC, pedrobaeza commented on product_variant_standard_price_update/models/product.py
> +    same_cost_variants = fields.Boolean(compute=_compute_same_cost_variants)
Put a label in this field for having a nice text when doing advanced searches

2016-12-16 04:34 UTC, sergio-teruel commented on product_variant_standard_price_update/models/product.py
> +            if cost.count(cost[0]) == len(cost):
Zero variants???

2016-12-16 04:37 UTC, sergio-teruel commented on product_variant_standard_price_update/models/product.py
> +    same_cost_variants = fields.Boolean(compute=_compute_same_cost_variants)
This is a compute field, we can not do search

2016-12-16 07:54 UTC, pedrobaeza commented on product_variant_standard_price_update/models/product.py
> +            if cost.count(cost[0]) == len(cost):
Exactly, this module prevents the creation of any variant until you confirm a sales/purchase order.

2016-12-16 07:55 UTC, pedrobaeza commented on product_variant_standard_price_update/models/product.py
> +    same_cost_variants = fields.Boolean(compute=_compute_same_cost_variants)
OK, you're right, but anyway, a nice label is always welcome, hehe

2016-12-16 07:55 UTC, pedrobaeza commented on product_variant_standard_price_update/README.rst
> +The module adds a button in template form for show a wizard to update the
This text should change if we remove the wizard (that we should).

2016-12-16 09:05 UTC, sergio-teruel commented on product_variant_standard_price_update/README.rst
> +The module adds a button in template form for show a wizard to update the
@pedrobaeza About the wizard i have decided keep it, becose it is more UX than mass editing action.

2016-12-16 09:27 UTC, sergio-teruel commented
@pedrobaeza changes done, except remove wizard :smile:

2016-12-18 23:40 UTC, pedrobaeza commented on product_variant_standard_price_update/README.rst
> +The module adds a button in template form for show a wizard to update the
But it's a lot of code to maintain that duplicates a function that already exists. And I don't agree it's more UX, as you have the same control and easiness with the other method.

2016-12-19 07:15 UTC, sergio-teruel commented on product_variant_standard_price_update/README.rst
> +The module adds a button in template form for show a wizard to update the
Where is this function?? How to update all cost variant price??

2016-12-19 07:49 UTC, pedrobaeza commented on product_variant_standard_price_update/README.rst
> +The module adds a button in template form for show a wizard to update the
You have 2 options:

* Set the price on the template, and it's propagated to all the variants, which is the most common need.
* Add the mass editing action on product.product, and change discretely the price on the variants you want.

2016-12-19 07:54 UTC, sergio-teruel commented on product_variant_standard_price_update/README.rst
> +The module adds a button in template form for show a wizard to update the
To point one, ok, when all variant standard price is the same, but not for second point, is better that user can update this prices from a button, the mass editing option is for technical users.

2016-12-19 07:58 UTC, pedrobaeza commented on product_variant_standard_price_update/README.rst
> +The module adds a button in template form for show a wizard to update the
I agree that we need a technical user for setting it, but not for using it, but is not commonly need, if a deployment need it, then we can add the mass editing action. Anyway, you're duplicating the variant list (in your wizard and in the smart-button variant list). I even prefer to add a static action like the mass-editing one than use that approach. Or are you going to add a wizard for every possible value that you set at variant level (weight, volume, EAN13...)?

2016-12-27 15:21 UTC, sergio-teruel commented
@pedrobaeza Changes done.

2017-01-23 09:50 UTC, sergio-teruel commented
@pedrobaeza Can you take a look?. Thanks

2017-06-09 00:29 UTC, rafaelbn approved these changes
Functionally tested 👍 many months in production... please @pedrobaeza review!

2017-06-09 00:37 UTC, pedrobaeza commented
What about my last comment? https://github.com/OCA/product-variant/pull/48#discussion_r92982671

2018-05-19 18:14 UTC, pedrobaeza commented
@sergio-teruel what happen with this PR? Can you check my comment?

2018-06-11 13:41 UTC, sergio-teruel commented
@pedrobaeza Fix readme

2018-06-11 16:56 UTC, pedrobaeza approved these changes

2018-06-11 16:56 UTC, merged