[MIG] purchase_variant_configurator_on_confirm: Migration to 10.0
OCA/product-variant pull request #67
Opened 2017-07-05 09:24 UTC by chienandalu

Purchase Variant Configurator On Confirm
========================================

Create product variants when confirming the purchase order.

cc @Tecnativa

2017-07-12 07:50 UTC, pedrobaeza requested changes

2017-07-12 07:50 UTC, pedrobaeza commented on purchase_variant_configurator_on_confirm/models/product_template.py
>                         date=time.strftime(DEFAULT_SERVER_DATE_FORMAT),
Why this strange default value? Upstream signature is `date=None`

2017-07-12 07:50 UTC, pedrobaeza commented on purchase_variant_configurator_on_confirm/models/product_template.py
>          self.ensure_one()
Let's try a trick here, creating a "in-memory" product record and calling the method on it:
```
product = self.env['product.product'].new({
    'product_tmpl_id': self.id,
    'name': self.name,
})
return product._select_seller(
    partner_id=partner_id, quantity=quantity, date=date, uom_id=uom_id,
)
```

2017-07-12 07:50 UTC, pedrobaeza commented on purchase_variant_configurator_on_confirm/models/purchase_order_line.py
> +        if self.env.uid == SUPERUSER_ID:
Why this unfolding? It's incorrect, as other users apart from admin can have access to several companies (through a parent company)

2017-07-12 07:50 UTC, pedrobaeza commented on purchase_variant_configurator_on_confirm/models/purchase_order_line.py
> +        """ Copy from standard: `PurcharseOrderLine.onchange_product_id` """
Have you reviewed v10 standard methods and their code? Maybe you can use similar techniques to the one I suggested above.

2017-07-12 15:49 UTC, chienandalu commented
@pedrobaeza I've tried to implementes your suggestions in the last commit. I'm dealing with this line though: https://github.com/Tecnativa/product-variant/blob/05c2db1ffc6fab320c168920a85059a8a260f6bf/purchase_variant_configurator_on_confirm/models/purchase_order_line.py#L19
I can't make self.product_id to get that context object properly although the context seems have the right object in the instant I want to pass it. What am I doing wrong? :confused:

2017-07-13 07:38 UTC, pedrobaeza commented
I don't get what are you trying to get with that context argument

2017-07-13 07:49 UTC, chienandalu commented
I try to pass the on memory product from template copy (https://github.com/Tecnativa/product-variant/blob/05c2db1ffc6fab320c168920a85059a8a260f6bf/purchase_variant_configurator_on_confirm/models/purchase_order_line.py#L25) to the original product_id_change function

2017-12-14 18:59 UTC, pedrobaeza approved these changes
I have been testing this and fixing the found problems, so I'm going to merge after a while this module for continuing improving things

2017-12-14 18:59 UTC, merged